name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - 'Chart.yaml'
      - 'values.yaml'
      - 'templates/**'

# Add permissions block
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3

      - name: Create Helm package
        run: |
          mkdir -p .cr-release-packages
          helm package . -d .cr-release-packages

      - name: Create index.yaml
        run: |
          helm repo index .cr-release-packages --url https://raw.githubusercontent.com/${{ github.repository }}/gh-pages/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .cr-release-packages
          publish_branch: gh-pages
          keep_files: true
          force_orphan: true
          enable_jekyll: false
          commit_message: "chore: update helm chart repository" 